export { default as HamburgerIcon } from "./Hamburger";
export { default as QuotesIcon } from "./Quotes";
export { default as ArrowIcon } from "./Arrow";
export { default as FacebookIcon } from "./Facebook";
export { default as TwitterIcon } from "./Twitter";
export { default as LinkedinIcon } from "./Linkedin";
export { default as InstagramIcon } from "./Instagram";
export { default as GooglePlayIcon } from "./GooglePlay";
export { default as AppStoreIcon } from "./AppStore";
